### ISSUE TITLE
feature: number of recurrence

### ISSUE THREAD

**Issue by alexgit2k** [niccokunzmann/python-recurring-ical-events#29] opened 2020-06-07 12:13 UTC
For recurring events I would like to have the number of the recurred event.

**Description**
An additional attribute ```X-RECURRENCE``` should be zero for the first event and for further recurrencces contain the number of the recurred event after the first event.

**Example**
A yearly recurring event starting at 2020-01-01:
```
BEGIN:VEVENT
DTSTART;VALUE=DATE:20000101
DTEND;VALUE=DATE:20000102
RRULE:FREQ=YEARLY
SUMMARY:Birthday
END:VEVENT
```

Queried for year 2020:
```
recurring_ical_events.of(calendar).at((2020, 1, 1))
```

Should return:
```
VEVENT({
	'SUMMARY'		: 'Birthday',
	'DTSTART'		: '20000101',
	'DTEND'			: '20000102',
	'X-RECURRENCE'		: 20
)
```

**Comment by niccokunzmann** [comment] 2020-06-12 13:39
Hi & thanks! This seems to be a nice feature. The recurrence is based on the [dateutil.rrule](https://dateutil.readthedocs.io/en/stable/rrule.html). I wonder if and how this can be implemented and if the rrule module provides some functionality or if it would need to be implemented.

**Comment by niccokunzmann** [comment] 2020-06-14 19:58
So, if dateutil.rrule does not provide the feature, we can agree on an interface or a strategy pattern or something to make this happen.

**Comment by alexgit2k** [comment] 2020-06-14 22:10
dateutil.rrule only returns an iterator to a list of datetime's: https://github.com/dateutil/dateutil/blob/master/dateutil/rrule.py#L776

**Comment by niccokunzmann** [comment] 2020-06-15 09:42
In this case, Imagine a daily event where 1000 events need to be skipped at the start - is there a way we do not need to generate them and instead use something like `len(ruleset)` This would reduce the computation overhead.

**Comment by niccokunzmann** [comment] 2022-04-08 18:02
I had a thought about this: The problem is also that just looking at rrule cannot solve it. Events might be edited and move to an earlier date. With that, it is not possible without generating all the events to make sure that their index is correct. Since this computational overhead is nothing we want to do each time, this feature will not be included by default. Also, since the computational effort equals to that done by the library when you retrieve all events from 1970 to this date, you can implement this requested feature as outlined by this algorithm:

```
define start_date and end_date
events = calendar events between(1970, end_date)
sort all events by their DTSTART
counts = defaultdict(default_value = 0)
for event in events:
  event.index=counts[event[UID]]
  counts[event[UID]] += 1
```

**Comment by niccokunzmann** [comment] 2022-04-08 18:06
I will close this issue now as out of scope of this module. If you like, you can implement an algorithm like this and we can talk about shipping it with this module. Feel free to re-open this issue to keep the conversation flowing and see you again :)

**Closed** 2022-04-08 18:06 UTC
Labels: enhancement
