### ISSUE TITLE
Daylight aware repeats

### ISSUE THREAD

**Issue by ttmx** [niccokunzmann/python-recurring-ical-events#48] opened 2020-10-26 11:24 UTC
Hello!
My script just stopped working today, and I'm preeetty sure its due to daylight savings time.
This would be the ICS file I'm using https://termbin.com/pws2
And here are my scripts https://github.com/ttmx/auto-uni , running python 3.8.6 and the latest RIE module version.
The part that isn't working properly is line 47 of openlink.py
`events = recurring_ical_events.of(cal).at(datetime.now(TZ))`
Where it seems like either datetime.now is not returning daylight aware times, or the RIE module isn't processing them how I would expect it to,

Weirdly enough, the entire countdown.py works.
I'm sure this is something on my end that I am doing wrong, and thus, didn't mark this as a bug.
Would there be any chance you could help me fix this? Totally understand if it is outside the purpose of github issues.

Thank you!

**Comment by niccokunzmann** [comment] 2020-10-26 15:43
If we can boil it down to a reproducible example, that could help. Can you show python code which creates the same object as datetime.now(TZ)? So we talk about the same object. 
Second: which outcome do you expect? I am still not quite good at reading ics files.
Thanks for providing so much information already!

**Comment by ttmx** [comment] 2020-10-26 17:29
Hey thank you for answering!
`TZ = timezone("Europe/Lisbon")` I have it the same as in the example file.
the datetime.now(TZ) is just the default libs `datetime`

I'm expecting it to return the events that are happening right now, but it is instead returning the events that will happen in an hour.
Example, right now its returning nothing, but an hour ago it was returning the RC-p event.
This calendar is from the same ICS file.
![image](https://user-images.githubusercontent.com/12669467/97206483-b0a1aa80-17b0-11eb-8d71-d0cb53ea573c.png)

Anything else I can provide? Thank you for your time!

**Comment by niccokunzmann** [comment] 2020-10-30 12:50
Can you provide python code to create a datetime for these cases: 1 no event expected but one given, 2 one event expected but none given, 3 an event given and expected, 4 no event given and none expected.

This will be enough to create reproducible tests.

For clarity, you can answer like
case 1: datetime.datetime(...)
...

**Comment by niccokunzmann** [comment] 2020-10-30 12:51
I would like to have tests to nail down the issue and find out where this error comes from.

**Comment by ttmx** [comment] 2020-11-02 12:30
Essentially, whenever I put that thing as the argument for `recurring_ical_events.of(cal).at(datetime_here)`, the events returned are sometimes mismatched by one hour, due to daylight savings. 

I'll always use the same "MDS-t" event, and the calendar I uploaded above as `cal` for simplicity.

Case 1:
```py
fakedate = datetime(2020,11,2,12,15,0,00)
events = recurring_ical_events.of(cal).at(fakedate)
```
This returns no events, even though MDS-t is happening at that time. ![image](https://user-images.githubusercontent.com/12669467/97866714-58186300-1d04-11eb-9612-97061970cc36.png)

Case 2:
```py
fakedate = datetime(2020,11,2,11,10,0,00)
events = recurring_ical_events.of(cal).at(fakedate)
```
This also returns no events, but nothing is happening at that time, so this is correct.

Case 3:
```py
fakedate = datetime(2020,11,2,11,40,0,00)
events = recurring_ical_events.of(cal).at(fakedate)
```
This does return the event, and it is happening here.

Due to these tests and some others, I have concluded the RIE function used, only returns correctly, if the event has already started AND if there is more than one hour left until the end of that event.
It seems something checking against the beginning is using daylight time, but when it checks against the end its using "regular" time.

Anything I can add? Thank you!

**Comment by niccokunzmann** [comment] 2020-11-03 13:40
Thanks. This is quite some info. I will look into it. If you like, you are also invited to create test cases. Maybe that is a learning opportunity for you.

**Comment by niccokunzmann** [comment] 2020-11-09 14:57
@ttmx I added a pull request and may go ahead with implementation. I am only rarely online these days, so if you want to do it, you are welcome! It is a well trodden path, see #49.

**Comment by ttmx** [comment] 2020-11-10 15:39
Just here to say I did not forget nor am I ignoring this. I want to eventually get around to it, but I do not have the know how or the time right now as I am in the middle of exam season.
Thank you for helping me out :)

**Comment by niccokunzmann** [comment] 2020-11-12 09:23
I can help with the know-how. Just let me know when the time is ripe.

**Comment by InduPrakash** [comment] 2020-11-17 11:43
I also noticed something off in this regards. I had created many recurring events before Daylight change happened and some events are not retrieved depending on the start_time passed to between().

```
localTZ = pytz.timezone("America/Chicago")

def dump_events(hour, minute):
    start_time = datetime.now()
    start_time = start_time.replace(
        hour=hour, minute=minute, second=0, microsecond=0)
    end_time = start_time.replace(hour=17, minute=0)

    start_time=localTZ.localize(start_time)
    end_time=localTZ.localize(end_time)

    feed_text = requests.get(calendar_feed).text
    calendar = Calendar.from_ical(feed_text)
    events = recurring_ical_events_of(calendar).between(start_time, end_time)

    print("Events between {} and {}".format(start_time, end_time))
    for event in events:
        summary = event["SUMMARY"]
        event_start = event["DTSTART"].dt
        print(event_start)

dump_events(9, 30)
dump_events(10, 0)
```

which generates this. Note that the 10:15 entry is lost when lookup is from 10:00

```
Events between 2020-11-17 09:30:00-06:00 and 2020-11-17 17:00:00-06:00
2020-11-17 12:30:00-06:00
2020-11-17 14:15:00-06:00
2020-11-17 10:15:00-06:00
2020-11-17 14:00:00-06:00
Events between 2020-11-17 10:00:00-06:00 and 2020-11-17 17:00:00-06:00
2020-11-17 12:30:00-06:00
2020-11-17 14:15:00-06:00
2020-11-17 14:00:00-06:00
```

**Comment by niccokunzmann** [comment] 2020-11-19 10:13
Hmm interesting.

**Comment by Cilyan** [comment] 2020-11-29 01:24
It looks related to these issues raised on `dateutil`, and in fact are due to how `pytz` behaves. It seems that using `dateutil.rrule` with `icalendar` is simply a no-go for DST timezones (or actually any timezone that appear to be changing in the course of time).

https://github.com/dateutil/dateutil/issues/641
https://github.com/dateutil/dateutil/issues/102
https://github.com/dateutil/dateutil/issues/88

Another example I stumbled upon and looks unlikely to be fixable easily:
```python
rru = dateutil.rrule.rrulestr("""DTSTART;TZID=Europe/Paris:20201010T153000
RRULE:FREQ=WEEKLY;WKST=MO;UNTIL=20201115T142959Z;BYDAY=SA,SU
"""
)
[d.astimezone(pytz.utc) for d in rru]
```
outputs what is expected:
```
[datetime.datetime(2020, 10, 10, 13, 30, tzinfo=<UTC>),
 datetime.datetime(2020, 10, 11, 13, 30, tzinfo=<UTC>),
 datetime.datetime(2020, 10, 17, 13, 30, tzinfo=<UTC>),
 datetime.datetime(2020, 10, 18, 13, 30, tzinfo=<UTC>),
 datetime.datetime(2020, 10, 24, 13, 30, tzinfo=<UTC>),
 datetime.datetime(2020, 10, 25, 14, 30, tzinfo=<UTC>),
 datetime.datetime(2020, 10, 31, 14, 30, tzinfo=<UTC>),
 datetime.datetime(2020, 11, 1, 14, 30, tzinfo=<UTC>),
 datetime.datetime(2020, 11, 7, 14, 30, tzinfo=<UTC>),
 datetime.datetime(2020, 11, 8, 14, 30, tzinfo=<UTC>),
 datetime.datetime(2020, 11, 14, 14, 30, tzinfo=<UTC>)]
```
 But now, using `pytz` in the same way as `icalendar` and `recurring_ical_events`:
```python
rru = dateutil.rrule.rrulestr("""
RRULE:FREQ=WEEKLY;WKST=MO;UNTIL=20201115T142959Z;BYDAY=SA,SU
""",
    dtstart=pytz.timezone("Europe/Paris").localize(datetime.datetime(2020, 10, 10, 15, 30))
)
[d.astimezone(pytz.utc) for d in rru]
```
outputs
```python
[datetime.datetime(2020, 10, 10, 13, 30, tzinfo=<UTC>),
 datetime.datetime(2020, 10, 11, 13, 30, tzinfo=<UTC>),
 datetime.datetime(2020, 10, 17, 13, 30, tzinfo=<UTC>),
 datetime.datetime(2020, 10, 18, 13, 30, tzinfo=<UTC>),
 datetime.datetime(2020, 10, 24, 13, 30, tzinfo=<UTC>),
 datetime.datetime(2020, 10, 25, 13, 30, tzinfo=<UTC>),
 datetime.datetime(2020, 10, 31, 13, 30, tzinfo=<UTC>),
 datetime.datetime(2020, 11, 1, 13, 30, tzinfo=<UTC>),
 datetime.datetime(2020, 11, 7, 13, 30, tzinfo=<UTC>),
 datetime.datetime(2020, 11, 8, 13, 30, tzinfo=<UTC>),
 datetime.datetime(2020, 11, 14, 13, 30, tzinfo=<UTC>),
 datetime.datetime(2020, 11, 15, 13, 30, tzinfo=<UTC>)]
```
which is wrong, both for the start times after the CEST to CET change and the last occurence is also incorrect.

**Comment by Cilyan** [comment] 2020-11-29 01:27
See also https://github.com/collective/icalendar/issues/162

**Comment by niccokunzmann** [comment] 2020-12-01 11:00
@iprak, you already added code. If you like to create a pull request which puts it into tests, this would be one step closer to implementing the expected behavior. Same for you @Cilyan, there is always the invitation. [This template](https://github.com/niccokunzmann/python-recurring-ical-events/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) documents the steps to be taken for a test-driven implementation. I am happy to help and @ttmx already added some tests. At the same time, I live in an Eco-Community right now, Internet far away, so I am slow to respond and do not take much time on programming.

**Comment by iprak** [comment] 2020-12-11 14:02
I submitted a PR (#51). The calendar data and the code are both close to my actual usage.

**Comment by niccokunzmann** [comment] 2020-12-27 15:55
@ttmx @iprak @Cilyan Thanks for getting involved in this. Both PRs are merged, release v0.1.21b should be on its way. I close this issue now, feel free to comment or open new issues!

**Closed by niccokunzmann** 2020-12-27 15:55 UTC

**Comment by ttmx** [comment] 2020-12-27 15:59
Does this fix the issue? I recall testing it some days ago and I still had the problem. 
Thank you!

**Comment by niccokunzmann** [comment] 2020-12-27 16:03
The tests are running. That should fix the issue, then. We can re-open it.

Also, be aware how to create a datetime object with the right time-zone: use tz.localize(dt) and not set it in the constructor.
